[Unit]
Requires=optiondata-meta-sync.service opt-my_influx-data-OptionData.mount opt-my_influx-wal-OptionData.mount
After=optiondata-meta-sync.service opt-my_influx-data-OptionData.mount opt-my_influx-wal-OptionData.mount

[Service]
LimitNOFILE=6553600
